spring:
  application:
    name: courier-tracking-app
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379


logging:
  level:
    org:
      springframework:
        cache: DEBUG
